#!/usr/bin/env bash

dry="0"

while [[ $# -gt 0 ]]; do
  if [[ $1 == "--dry" ]]; then
    dry="1"
  fi
  shift
done

log() {
  if [[ $dry == "1" ]]; then
    echo "[DRY_RUN]: $*"
  else
    echo "$*"
  fi
}

execute() {
  log "execute : $*"
  if [[ $dry == "1" ]]; then
    return
  fi
  "$@"
}

log "-----------------dev-env-----------------"

copy_dir() {
  from=$1
  to=$2

  pushd "$from" >/dev/null || exit
  dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
  for dir in $dirs; do
    execute rm -rf "$to/$dir"
    execute cp -r "$dir" "$to/$dir"
  done
  popd >/dev/null || exit
}

copy_file() {
  from=$1
  to=$2
  name=$(basename "$from")

  execute rm -f "$to/$name"
  execute cp -r "$from" "$to/$name"
}

copy_dir ./dotfiles/.config "$HOME/.config"
copy_file ./dotfiles/.zshrc "$HOME"
copy_file ./dotfiles/.config/starship.toml "$HOME/.config"
